[package]
name = "kyubey"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.3"
color-eyre = "0.6.3"
sqlx = { version = "0.8.5", features = ["runtime-tokio", "postgres"] }
tokio = { version = "1.44.2", features = ["rt-multi-thread"] }
tower-http = { version = "0.6.2", features = ["trace"] }
tracing-subscriber = "0.3.19"
