name: Rust

on:
  pull_request:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Just
        run: sudo apt install just
      - name: Check
        run: just check

  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Just
        run: sudo apt install just
      - name: Clippy
        run: just clippy

  fmt-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Just
        run: sudo apt install just
      - name: Format
        run: just fmt-check

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Just
        run: sudo apt install just
      - name: Tests
        run: just test

  sqlx-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Just
        run: sudo apt install just
      - name: SQLx Cache Check
        run: just sqlx-check

  deny:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Just
        run: sudo apt install just
      - name: Cargo Deny Checks
        run: just deny
